freeCodeCamp/curriculum-helpers

- .editorconfig
- .eslintignore
- .gitattributes
- .gitignore
- README.md
- lib/__tests__/curriculumHelpers.test.js
- lib/index.js
- package-lock.json
- package.json
This PR creates the ideal package config for publishing to npm
Checklist:
Closes #XXXXX
> feat: generate node package with yeoman

- README.md
- lib/css-helper.ts
- lib/index.ts
> fix: no need for css helper

- package-lock.json
This reverts commit 34a840f5020f089ff651196a6a9c75f4d1861aa4.
> Revert "fix: package naming (#30)"

- package-lock.json
- package.json
> chore: release version v1.2.0

- .eslintrc.json
- .github/workflows/ci.yml
- lib/__fixtures__/curriculum-helper-css.ts
- lib/__fixtures__/curriculum-helpers-html.ts
- lib/__fixtures__/curriculum-helpers-javascript.ts
- lib/__fixtures__/curriculum-helpers-remove-white-space.ts
- lib/__tests__/css-helper.test.ts
- lib/__tests__/curriculum-helper.test.ts
- lib/class/node.ts
- lib/compile.ts
- lib/index.ts
- lib/languages.ts
- lib/option-types.ts
- lib/parse.ts
- lib/strip.ts
- package-lock.json
- package.json
> chore: enable linting in workflow

- .npmignore
- package-lock.json
- package.json
- add `python.getBlock`
- add `python.removeComments`
> feat(1.3.0): release

- docs/python.md
- docs/tools/helpers.js
- lib/index.ts
Related #106 
Closes #109
Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/52685
Also, fixes requiring a new line at the beginning of blocks (requiring function defs to not be at beginning of file)
> fix(python): add docs + newline fix

- package-lock.json
- package.json
> chore: release version v2.0.0

- package.json
Checklist:
To check `npm publish --dry-run`
> fix: bundle before publishing

- package-lock.json
- package.json
> chore: release version v2.0.1

- package-lock.json
- package.json
> chore: release v2.0.3

- python/py_helpers.py
- python/py_helpers.test.py
Checklist:
There's also a small fix: `find_if_bodies` wasn't returning valid `Node`s. Now it is.
> refactor: Chainable -> Node

- lib/class/node.ts
- lib/compile.ts
- lib/index.ts
- lib/languages.ts
- lib/parse.ts
- lib/strip.ts
- tsconfig.json
- refactor: strict types for index.ts
- refactor: fix types for parse and node
Checklist:
Closes #XXXXX
> fix: enable strict mode for TypeScript

- docs/python.md
> docs: add section for ast helpers

- python/py_helpers.test.py
- refactor: allow unittest to discover suites
- chore: format
Checklist:
> refactor: simplify test suites

- package-lock.json
- package.json
> chore: release v2.1.0

- package-lock.json
- package.json
> chore: release v2.1.1

- python/py_helpers.py
- python/py_helpers.test.py
Checklist:
Handles the case where the conditional in an `if` statement is a string.
> fix: conditional string equivalence

- package-lock.json
- package.json
> chore: release v2.2.0

- package-lock.json
- package.json
> chore: release v2.2.1

- package-lock.json
- package.json
> chore: release v2.3.0

- python/py_helpers.py
- python/py_helpers.test.py
> fix: make len() return values for all Node types

- python/py_helpers.py
- python/py_helpers.test.py
> feat(python): add ast-based helpers for loops

- package-lock.json
- package.json
> chore: release v2.4.0

- docs/python.md
> docs(python): update ast-based helpers docs

- python/py_helpers.py
- python/py_helpers.test.py
> feat: add has_pass python helper

- python/py_helpers.py
> chore: remove old comment

- python/py_helpers.py
- python/py_helpers.test.py
Checklist:
This PR unifies some of the previous helper functions into `find_conditions` and `find_bodies`, which can be applied for loops and conditional statements.
> chore(python): rename find_x_bodies and find_x_conditions ast helpers

- python/py_helpers.py
- python/py_helpers.test.py
Checklist:
`Node()[0]` still raises an exception, but hopefully it will make sense now.
> fix(python): handle indexing of empty Nodes

- python/py_helpers.py
- python/py_helpers.test.py
> fix(python): prevent has_pass to be called on if, while, for

- package-lock.json
- package.json
> chore: release v3.0.0

- docs/python.md
Checklist:
Related to #163, #159
> docs(python): update python docs

- package-lock.json
- package.json
> chore: release v3.0.1

- python/py_helpers.py
- python/py_helpers.test.py
> feat: add is_empty helper

- docs/python.md
> docs: add is_empty

- python/py_helpers.py
- python/py_helpers.test.py
Checklist:
Adding new ast-based helpers. Work in progress...
> feat(python): adding new ast helpers

- docs/python.md
> docs(python): fix wrong method name and improve examples

- python/py_helpers.py
- python/py_helpers.test.py
> fix(python): has_args helper

- python/py_helpers.py
- python/py_helpers.test.py
> feat(python): add new ast helpers

- .github/workflows/ci.yml
- python/py_helpers.py
- python/py_helpers.test.py
Checklist:
Closes #166 
In the end I decided against using lint-staged, but we can add it later if contributors accidentally commit unformatted code too often.
> ci: require code to be formatted

- .github/workflows/ci.yml
> ci: update to actions/checkout@v4

- python/py_helpers.py
- python/py_helpers.test.py
Checklist:
Closes nothing yet, but it should let us address https://github.com/freeCodeCamp/freeCodeCamp/issues/52411 when incorporated into the python worker
> feat: add tools for formatting python exceptions

- package-lock.json
- package.json
> release: v3.3.1

- package-lock.json
- package.json
> chore: release v3.3.2

- package-lock.json
- package.json
> chore: release v3.4.0

- docs/python.md
> docs: update python docs

- python/py_helpers.py
- python/py_helpers.test.py
> feat: add find_variables ast-helper

- package-lock.json
- package.json
> chore: release v3.5.0

- python/py_helpers.py
- python/py_helpers.test.py
> feat: match/case ast-based helpers

- package-lock.json
- package.json
> chore: release v3.6.0

- package-lock.json
- package.json
> chore: release v3.7.0

- package-lock.json
- package.json
> chore: release v3.8.0

- lib/__fixtures__/curriculum-helper-css.ts
- lib/__tests__/css-helper.test.ts
Checklist:
Closes #XXXXX
While there is already an example of using the pseudo-class selector of ":root", I want to cover an additional base of using a selector with a class.
> chore: add a pseudo-class test case

- .github/workflows/mdbook.yml
> chore: update actions/deploy-pages to latest

- package-lock.json
- package.json
> chore: release v3.9.0

- package.json
Checklist:
One is all you need.
> chore: remove second jest config

- package.json
While the build will break if tsc cannot compile, this gives cleaner errors.
Checklist:
Closes #XXXXX
> tools: typecheck when linting

- package.json
> chore: release v3.10.0

- package.json
> chore: release v3.11.0

- docs/python.md
> docs: remove reference to get_nth_statement python helper

- package.json
> chore: release v4.0.0

- package.json
> chore: release v4.1.0

- eslint.config.mjs
- package.json
- packages/dom-evaluator/src/dom-test-evaluator.ts
- packages/helpers/lib/index.ts
- packages/javascript-evaluator/src/javascript-test-evaluator.test.ts
- packages/javascript-evaluator/src/javascript-test-evaluator.ts
- packages/main/src/declarations.d.ts
- packages/main/src/index.test.ts
- packages/main/src/index.ts
- packages/main/src/test-runner.ts
- packages/main/src/timeout.test.ts
- packages/python-evaluator/src/python-test-evaluator.ts
- packages/shared/src/format.test.ts
- packages/shared/src/format.ts
> chore: apply eslint to more files and fix errors

- package.json
> chore: release v4.4.0

- webpack.config.js
> fix: generate types for production build

- package.json
> chore: release v4.5.1

- package.json
Checklist:
Most of the time `pnpm clean:ts` is sufficient, but having `node_module` removal be part of the main `clean` script makes debugging build failures a bit easier.
> chore: include package removal in clean

- package.json
Checklist:
Otherwise the build will fail since all the node_modules get deleted.
> fix: only clean build artifacts before publishing

- packages/tests/integration-tests/index.test.ts
Checklist:
There was some repetition.
> refactor: clean up tests

- packages/main/src/test-runner.ts
- packages/tests/integration-tests/index.test.ts
Checklist:
This is mostly syntactic sugar for now, but it will be very useful once I add the afterAll hook.
> feat: add runAllTests function

- packages/dom-evaluator/src/dom-test-evaluator.ts
- packages/javascript-evaluator/src/javascript-test-evaluator.ts
- packages/main/src/test-runner.ts
- packages/python-evaluator/src/python-test-evaluator.ts
> refactor: use awaitable post to pass messages
