freeCodeCamp/curriculum-helpers

lib/__tests__/css-helper.test.ts
lib/index.ts

Checklist:
Add two new methods to the `CSSHelp` class for testing challenges where multiple CSS selectors are valid. Example: https://github.com/freeCodeCamp/freeCodeCamp/pull/52379

feat: add 2 CSS helper methods

---

lib/__tests__/python.test.ts
lib/index.ts

Checklist:
Adds a helper I think we might want to use in some Python curriculum tests. As such, I created a separate module for the code.
<details>
<summary>Example Code to Test</summary>
```python
NUMBER_OF_DISKS = 3
number_of_moves = 2 ** NUMBER_OF_DISKS - 1
rods = {
'A': list(range(NUMBER_OF_DISKS, 0, -1)),
'B': [],
'C': []
}
def move(n, source, target, auxiliary):
for i in range(number_of_moves):
if (i + 1) % 3 == 1:
print(f'Move {i + 1} allowed between {source} and {target}')
forward = False
if len(rods[target]) == 0:
forward = True
elif (i + 1) % 3 == 2:
print(f'Move {i + 1} allowed between {source} and {auxiliary}')
elif (i + 1) % 3 == 0:
print(f'Move {i + 1} allowed between {auxiliary} and {target}')
```
</details>
<details>
<summary>Example test</summary>
```js
// Test if …
```

feat: add python getDef helper

---

lib/__tests__/python.test.ts
lib/index.ts

This fixes issues where:
- Function is defined at end of string
- There are no word/`#` characters
- Technically, Python functions cannot have new line characters in the `def name(` part
- Only `' '` (space) characters
- **Note:** Surprisingly, there can be new line characters within the function params 🤷‍♂️ (_WHY PYTHON! WHY!_)
- The function `def` return no longer includes the superfluous `\n`

fix: match defs at end of string

---

.eslintignore
.npmignore
lib/compile.ts
lib/index.ts
lib/parse.ts
lib/strip.ts
package-lock.json
package.json
webpack.config.js

**Changes**
- Uses Webpack as the bundler
- Inline package code instead of alternate entry points
**Advantages**
- Now should be able to add `babeliser`
- Smaller package thanks to minification + sourcemap
- Should be compatible in Node + Browser
**Disadvantages**
- None?

chore: use webpack to build

---

webpack.config.js

> When targeting a library, especially when libraryTarget is 'umd', this option indicates what global object will be used to mount the library. To make UMD build available on both browsers and Node.js, set output.globalObject option to 'this'. Defaults to self for Web-like targets.
> The return value of your entry point will be assigned to the global object using the value of output.library.name. Depending on the value of the target option, the global object could change respectively, e.g., self, global, or globalThis.
https://webpack.js.org/configuration/output/
We should probably set the other values as well?

fix: set webpack global Object to "this"

---

package.json
webpack.config.js

Tested like this:
```js
// index.js
import * as __helpers from "@freecodecamp/curriculum-helpers/dist/index.node.js";
console.log(__helpers);
```
```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Curriculum Helpers</title>
</head>
<body>
<h1>Curriculum Helpers</h1>
</body>
<script type="module">
import * as __helpers from "./node_modules/@freecodecamp/curriculum-helpers/dist/index.browser.js";
console.log(__helpers);
</script>
</html>
```

fix: output multiple targets

---

docs/css.md

- fix(docs): prevent CSS code from being executed
- refactor(docs): newlines around decribe blocks
Checklist:
I was a little confused why this was acting like it was runnable when it wasn't, so I changed it. The newlines just make it a touch more readable imo.

docs: update css section

---

.gitpod.yml

Adds a `.gitpod.yml` with config to install mdbook and mdbook-admonish (tooling needed for docs).

chore(.gitpod): init with mdbook

---

package.json

They need to be declared in package.json in order for importing packages
to find them.
Checklist:

fix: make types discoverable

---

docs/python.md
python/py_helpers.py
python/py_helpers.test.py

Checklist:
@ShaunSHamilton while working on https://github.com/freeCodeCamp/freeCodeCamp/pull/53125 I realised that it would be nice to simply get the code at certain points. Since `repr` gives you the AST dump, I figured `str` could give us the `unparse`d string.

feat: more ast helpers: __str__ and find_body

---

docs/curriculum-helpers.md
lib/__tests__/curriculum-helper.test.ts
lib/index.ts

Checklist:
Joining two regexes together doesn't take a lot of code, but it does clutter the tests more than I'd like. Hence this PR.

feat: add concat regex helper

---

python/py_helpers.py
python/py_helpers.test.py

Checklist:
@Dario-DC I can't think of a test for `find_conditions` right now, so if you've got something, please push a commit. If not, don't worry about it. We can keep expanding the coverage if we find more issues!

fix: recurse properly when unwinding nested ifs

---

.editorconfig

The probability that I remember to ctrl + k ctrl + s is roughly 0, so
this saves me a lot of pain.
Checklist:
https://github.com/freeCodeCamp/curriculum-helpers/pull/190 (which I promise I will review soon!) reminded me that the whitespace trimming is still a nuisance. Hopefully this fixes it.

chore: stop editors from trimming fixtures

---

python/py_helpers.py
python/py_helpers.test.py

feat: async/await, return, comprehension ast-based helpers

---

package.json

If tsconfig's moduleResolution is set to Node16 or NodeNext it stops using the "types" property in package.json and, instead, relies on "types" inside "exports".
This now supports both.
Checklist:
Closes #XXXXX

build: support modern node resolution

---

python/py_helpers.py
python/py_helpers.test.py

Checklist:
Updates the error formatter so that it renames the File when there is a syntax error.
Given the code `var=` 
```py
>>> Traceback (most recent call last):
File "<exec>", line 1
var=
^
SyntaxError: invalid syntax
```
becomes
```pyt
>>> Traceback (most recent call last):
File "main.py", line 1
var=
^
SyntaxError: invalid syntax
```

fix: rename syntax errors

---

docs/curriculum-helpers.md
lib/__tests__/curriculum-helper.test.ts
lib/index.ts

Checklist:
TODO
The docs should explain this pretty well, but the gist is: this function provides a regex to match function expressions/declarations and arrow functions.

feat: add helper for matching function strings

---

lib/__tests__/curriculum-helper.test.ts
lib/index.ts

Checklist:
Use case:
```js
const sum = xs.reduce(
(accumulator, currentValue) => accumulator + currentValue, 0
);
```
If you want to just check that the callback exists, `functionRegex` should not care about the arguments. 
In the main repo, the third test of:
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-oop-by-building-a-shopping-cart/63eedebb0ec0231ff1cede1a.md

feat: match functions without knowing the params

---

lib/__fixtures__/curriculum-helpers-javascript.ts
lib/__tests__/javascript-helper.test.ts
lib/index.ts

Checklist:
Closes #247
Parameters that are passed in that are de-structured are being read as if they were single variables. Additionally spread variables deserve to be read if they're using the spread operator.

chore: capture destructured parameters

---

lib/index.ts

Checklist:
Closes #XXXXX
I found this typo and had to fix it.

chore: fix misspelling in comment on selectorsFromSelector

---

.babelrc
docs/curriculum-helpers.md
lib/__tests__/curriculum-helper.test.tsx
lib/index.ts
package-lock.json
package.json

This function handles creating and mounting React component. It then returns a DOM element with the mounted component, so that tests can inspect it.
Checklist:
In https://github.com/freeCodeCamp/freeCodeCamp/pull/58410 I added it as part of the client, but I think it's better as a helper (it's easier to test and document in this repo).

feat: add prepTestComponent

---

lib/__tests__/curriculum-helper.test.tsx
lib/parse.ts
tsconfig.json

Checklist:
`/(")[^\1]` Is not, it seems, a valid regex. The idea was that `[^\1]` should be "not the first backreference", however backreferences cannot be used in character classes. Except, obviously, this has been working just fine.
Regardless of the root cause, the new regex is definitely valid and so should be fine.
Ref: https://github.com/freeCodeCamp/curriculum-helpers/pull/146#issuecomment-2394038533

fix: use valid regex syntax

---

docs/curriculum-helpers.md
lib/__tests__/curriculum-helper.test.tsx
lib/index.ts

Checklist:
- - -
- Helper dealing with regex that should allow specific parts in any order. Ie. for regex composed from parts `a`, `b` and `c`, which checks code written as `a || b || c`, it should match both `a || b || c` and `b || a || c`, and any other permutation.
- Name is a bit rough.
- Default `elementsSeparator` is a bit arbitrarily picked...
- A bit of context https://github.com/freeCodeCamp/freeCodeCamp/pull/53606#issuecomment-1960408047
Capturing groups in individual regex
- It's rather easy to think of situation where it might be handy - ie. `("|')thing\1`, `(?<m>"|")thing\k<m>`. It'd be good to support it.
- If individual regex has capturing group, it will likely break. Named capturing group will surely break - group names have to be unique. Reference to non-named capturing …

feat: permutateRegex

---

docs/SUMMARY.md
docs/javascript.md
lib/__tests__/babeliser.test.ts
lib/class/babeliser.ts
lib/index.ts
package.json
pnpm-lock.yaml
tsconfig.json

I have lost count what attempt number this is at getting this going.

feat: add babeliser

---

lib/__tests__/tower.test.ts
lib/class/tower.ts
lib/index.ts
package.json
pnpm-lock.yaml
tsconfig.json

This is a more basic AST explorer than Babeliser. I am still not 100% about the API, but have already started adding/using it in:
https://github.com/freeCodeCamp/back-end-development-and-apis/blob/64f5270dab04eb80026aed10f91dfdfda4dfda3d/curriculum/locales/english/learn-npm-by-building-an-npm-module.md?plain=1#L1298-L1317

feat: basic js ast explorer

---

lib/__tests__/curriculum-helper.test.tsx
lib/index.ts

Checklist:
I based this on @ShaunSHamilton's `spyOn` helper function in https://github.com/freeCodeCamp/freeCodeCamp/pull/59518, and generalised it a little.

feat: add a helper to spy on the callbacks passed to functions

---

python/py_helpers.py
python/py_helpers.test.py

Checklist:
Closes #XXXXX
The main purpose of this helper would be to verify that specific built-in functions or methods (such as `.sort()` or `sorted()`) are not used by campers to solve DSA labs.
Not sure if we need it, but you can either choose to check that the method/function `spam` is called anywhere within a specific function `foo` with:
```py
_Node(_code).block_has_call(spam, foo)
```
or verify that `spam` is called anywhere within the user's code:
```py
_Node(_code).block_has_call(spam)
```

feat: add a helper to find if a function has a func/method call

---

packages/main/src/index.ts

This allows consumers to use the type directly, rather than relying on
declaration merging.
Checklist:
Closes #XXXXX

feat: export FCCTestRunner

---

packages/main/src/index.test.ts
packages/main/src/timeout.test.ts
packages/shared/tooling/webpack-compile.ts
vitest-puppeteer.config.cjs
vitest.config.mjs
webpack.config.js

While it's not necessary if the source is unchanged, it's much nicer than having to manually quit and restart the tests.
I also removed http-server's caching so that the tests always run against the latest code.
Checklist:

refactor(test): recompile source before each test

---

vitest.config.mjs

All unit tests follow the pattern filename.ts -> filename.test.ts, so vitest now always looks for the related test.
Checklist:

test: only watch .ts files, trigger related tests

---

packages/dom-evaluator/src/dom-test-evaluator.ts
packages/javascript-evaluator/src/javascript-test-evaluator.ts
packages/main/integration-tests/index.test.ts
packages/main/src/index.ts
packages/main/src/test-runner.ts
packages/python-evaluator/src/python-test-evaluator.ts
packages/shared/src/interfaces/test-evaluator.ts

Checklist:
The DOM evaluator shares state between tests, so a `beforeAll` hook is necessary for anything that needs to be setup just once. Using `beforeAll` for worker evaluators (JS and Python) is less vital since they have more isolated tests.  However, there are ways to get around the isolation. For example, the virtual filesystem that pyodide gives access to is persisted between tests, as is the `globalThis` object.
With that in mind, this makes all the evaluators handle both `beforeEach` and `beforeAll`.

feat: make all evaluators handle before hooks

---

packages/dom-evaluator/src/dom-test-evaluator.ts
packages/javascript-evaluator/src/javascript-test-evaluator.ts
packages/python-evaluator/src/python-test-evaluator.ts

This should make it easier to do unit testing, since globalThis is available in all environments.
Checklist:

refactor: use globalThis

---

package.json
pnpm-lock.yaml
vitest.config.mjs
vitest.integration.config.mjs
vitest.unit.config.mjs

Vitest has projects which are a great way to organise test config, but watchTriggerPatterns is global, not per project. If you want a single project to behave like e2e tests (i.e. run if the source changes) and another like unit tests (i.e. run if a file they're importing changes), it doesn't work.
Concurrently fixes this because it handles running the projects and they handle (separately) which tests should run.

fix: use concurrently to give correct watch behaviour

---

README.md
package.json

It's still quite frustrating to use, but it's now possible to do simple stuff (force tests to re-run, for example).
Checklist:

chore: allow input to be passed in watch mode

---

packages/python-evaluator/src/python-test-evaluator.ts
packages/tests/integration-tests/index.test.ts
packages/tests/integration-tests/timeout.test.ts

Checklist:
Now object form tests will effectively be ignored since the object will be evaluated, but not the test function.

feat: drop support for object form python tests

---

packages/python-evaluator/src/python-test-evaluator.ts
packages/tests/integration-tests/index.test.ts

It's important to mock input so that unexpected input statements don't immediately break tests
but it needs to be possible to override that with beforeEach
Checklist:

fix: input mock order

---

packages/dom-evaluator/src/dom-test-evaluator.ts
packages/javascript-evaluator/src/javascript-test-evaluator.ts
packages/python-evaluator/src/python-test-evaluator.ts
packages/shared/src/interfaces/test-evaluator.ts
packages/tests/integration-tests/index.test.ts

- **refactor: put afterEach at end of runTest**
- **feat: fail test if afterEach throws**
Checklist:
Have errors in afterEach fail the test to allow us to immediately see that something has gone wrong.
Note: breaking.

feat: throw in afterEach

---

packages/python-evaluator/src/python-test-evaluator.ts
packages/tests/integration-tests/index.test.ts

Checklist:
Tests should not automatically fail if there's an error in the source. Various tests are only interested in using regexes on the code.

fix: handle invalid python syntax

---

packages/python-evaluator/src/python-test-evaluator.ts
packages/tests/integration-tests/index.test.ts
packages/tests/integration-tests/timeout.test.ts

- **Revert "fix: handle invalid python syntax (#408)"**
- **Revert "feat: drop support for object form python tests (#401)"**
- **feat: stop supporting simple tests + input arrays**
Checklist:
While the object syntax is a little awkward, it makes it easier to test python code that does not terminate. Simply because if the test isn't in the object form, the python code is not evaluated.
The simpler tests, by design, always ran the python code and so would timeout if evaluation never terminated.

feat: reinstate support for object syntax
